image: andrewmontagne/byond:latest

build:
  variables:
    TERM: dumb
  tags:
    - docker-runner
  script:
    - make build
  artifacts:
    paths:
      - prometheus.dmb
      - prometheus.rsc
    expire_in: 1 month