image: andrewmontagne/byond:latest

lint:
  variables:
    TERM: dumb
  tags:
    - docker-runner
  script:
	- make lint
	
mapmerge:
  variables:
    TERM: dumb
  tags:
    - docker-runner
  script:
    - make mapmerge-test

build:
  variables:
    TERM: dumb
  tags:
    - docker-runner
  script:
    - make build
  artifacts:
    paths:
      - prometheus.dmb
      - prometheus.rsc
    expire_in: 1 month
  dependencies:
	- lint
	- mapmerge
