image: andrewmontagne/byond:latest

stages:
  - lint
  - build

lint:
  stage: lint
  variables:
    TERM: dumb
  tags:
    - docker-runner
  script:
    - make lint

mapmerge:
  stage: lint
  variables:
    TERM: dumb
  tags:
    - docker-runner
  script:
    - make mapmerge-test

compile:
  stage: build
  variables:
    TERM: dumb
	BUILD_RELEASE: "true"
  needs: [lint, mapmerge]
  tags:
    - docker-runner
  script:
    - make build
  artifacts:
    paths:
      - prometheus.dmb
      - prometheus.rsc
    expire_in: 1 week
