/obj/secure_closet/security1/New()
	..()
	sleep(2)
	new /obj/item/device/flash(src)
	new /obj/item/clothing/under/color/red(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/suit/armor/vest(src)
	new /obj/item/clothing/head/helmet(src)
	new /obj/item/clothing/glasses/sunglasses(src)
	new /obj/item/weapon/baton(src)
	return

/obj/secure_closet/security2/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/det( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/head/det_hat( src )
	new /obj/item/clothing/suit/det_suit( src )
	new /obj/item/clothing/gloves/black( src )
	new /obj/item/weapon/storage/lglo_kit( src )
	new /obj/item/device/detective_scanner( src )
	new /obj/item/device/detective_scanner( src )
	new /obj/item/device/detective_scanner( src )
	return

/obj/secure_closet/highsec/New()
	..()
	sleep(2)
	new /obj/item/device/flash( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/armor/vest( src )
	new /obj/item/clothing/head/helmet( src )
	return

/obj/secure_closet/hos/New()
	..()
	sleep(2)
	new /obj/item/device/flash( src )
	new /obj/item/clothing/under/rank/head_of_security( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/armor/vest( src )
	new /obj/item/clothing/head/helmet( src )
	return
